id: footers
version: 1
snapshot:
  collections:
    - collection: linotype_block__footers
      meta:
        accountability: all
        archive_app_filter: true
        archive_field: status
        archive_value: archived
        collapse: open
        collection: linotype_block__footers
        color: null
        display_template: "{{reference}}"
        group: linotype_blocks
        hidden: false
        icon: view_compact
        item_duplication_fields: []
        note: ""
        preview_url: null
        singleton: false
        sort: 12
        sort_field: sort
        translations:
          - plural: Footers
            language: en-US
            singular: Footer
            translation: Footers
        unarchive_value: draft
        versioning: false
      schema:
        name: linotype_block__footers
  fields:
    - collection: linotype_block__footers
      field: id
      type: integer
      meta:
        collection: linotype_block__footers
        conditions: null
        display: null
        display_options: null
        field: id
        group: null
        hidden: true
        interface: numeric
        note: null
        options: null
        readonly: true
        required: false
        sort: 1
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: id
        table: linotype_block__footers
        data_type: int unsigned
        default_value: null
        max_length: null
        numeric_precision: 10
        numeric_scale: 0
        is_nullable: false
        is_unique: false
        is_primary_key: true
        is_generated: false
        generation_expression: null
        has_auto_increment: true
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__footers
      field: infos
      type: text
      meta:
        collection: linotype_block__footers
        conditions: null
        display: null
        display_options: null
        field: infos
        group: null
        hidden: false
        interface: input-rich-text-html
        note: null
        options:
          toolbar:
            - bold
            - customLink
            - italic
            - strikethrough
            - subscript
            - superscript
            - underline
        readonly: false
        required: false
        sort: 11
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: infos
        table: linotype_block__footers
        data_type: text
        default_value: null
        max_length: 65535
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__footers
      field: links
      type: json
      meta:
        collection: linotype_block__footers
        conditions: null
        display: formatted-json-value
        display_options:
          format: "{{title}}"
        field: links
        group: null
        hidden: false
        interface: list
        note: null
        options:
          fields:
            - field: title
              name: title
              type: text
              meta:
                type: text
                field: title
                width: full
                required: true
                interface: input
            - field: url
              name: url
              type: string
              meta:
                type: string
                field: url
                width: full
                required: false
                interface: input
            - field: description
              name: description
              type: text
              meta:
                field: description
                width: full
                type: text
                required: false
                interface: input-rich-text-html
                options:
                  toolbar:
                    - bold
                    - italic
                    - underline
                    - numlist
                    - bullist
                    - customLink
            - field: list
              name: list
              type: json
              meta:
                type: json
                field: list
                width: full
                options:
                  fields:
                    - field: style
                      name: style
                      type: string
                      meta:
                        field: style
                        width: full
                        type: string
                        required: true
                        interface: select-dropdown
                        options:
                          choices:
                            - text: Simple
                              value: simple
                            - text: Big
                              value: big
                            - text: Action
                              value: action
                    - field: title
                      name: title
                      type: text
                      meta:
                        type: text
                        field: title
                        width: full
                        required: true
                        interface: input
                    - field: url
                      name: url
                      type: string
                      meta:
                        type: string
                        field: url
                        width: full
                        required: true
                        interface: input
                  addLabel: New sub-menu
                  template: "{{title}}"
                required: false
                interface: list
          template: "{{title}}"
        readonly: false
        required: false
        sort: 7
        special:
          - cast-json
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: links
        table: linotype_block__footers
        data_type: longtext
        default_value: null
        max_length: 4294967295
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__footers
      field: logo
      type: uuid
      meta:
        collection: linotype_block__footers
        conditions: null
        display: null
        display_options: null
        field: logo
        group: null
        hidden: false
        interface: file-image
        note: null
        options:
          crop: false
        readonly: false
        required: false
        sort: 5
        special:
          - file
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: logo
        table: linotype_block__footers
        data_type: char
        default_value: null
        max_length: 36
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: directus_files
        foreign_key_column: id
    - collection: linotype_block__footers
      field: logo_size
      type: integer
      meta:
        collection: linotype_block__footers
        conditions: null
        display: null
        display_options: null
        field: logo_size
        group: null
        hidden: false
        interface: input
        note: null
        options:
          max: 800
          min: 10
          step: 10
        readonly: false
        required: false
        sort: 6
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: logo_size
        table: linotype_block__footers
        data_type: int
        default_value: 150
        max_length: null
        numeric_precision: 10
        numeric_scale: 0
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__footers
      field: reference
      type: string
      meta:
        collection: linotype_block__footers
        conditions: null
        display: raw
        display_options: null
        field: reference
        group: null
        hidden: false
        interface: input
        note: null
        options:
          iconLeft: flag
          placeholder: Define a unique reference for this block
          trim: true
        readonly: false
        required: true
        sort: 3
        special: null
        translations:
          - language: en-US
            translation: Reference
        validation: null
        validation_message: null
        width: half
      schema:
        name: reference
        table: linotype_block__footers
        data_type: varchar
        default_value: null
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__footers
      field: socials_links
      type: json
      meta:
        collection: linotype_block__footers
        conditions: null
        display: formatted-json-value
        display_options:
          format: "{{name}}"
        field: socials_links
        group: null
        hidden: false
        interface: list
        note: null
        options:
          addLabel: New
          fields:
            - field: icon
              name: icon
              type: uuid
              meta:
                type: uuid
                field: icon
                width: half
                options:
                  template: "{{$thumbnail}} Name"
                  selectedCollection: directus_files
                required: true
                interface: uuid-file-image
            - field: icon_height
              name: icon_height
              type: integer
              meta:
                type: integer
                field: icon_height
                width: half
                options:
                  placeholder: "30"
                required: false
                interface: input
            - field: name
              name: name
              type: string
              meta:
                type: string
                field: name
                required: true
                interface: input
            - field: title
              name: title
              type: text
              meta:
                field: title
                width: full
                type: text
                required: false
                interface: input
            - field: link
              name: link
              type: string
              meta:
                type: string
                field: link
                width: full
                required: false
                interface: input
          template: "{{name}}"
        readonly: false
        required: false
        sort: 9
        special:
          - cast-json
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: socials_links
        table: linotype_block__footers
        data_type: longtext
        default_value: null
        max_length: 4294967295
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__footers
      field: socials_title
      type: text
      meta:
        collection: linotype_block__footers
        conditions: null
        display: null
        display_options: null
        field: socials_title
        group: null
        hidden: false
        interface: input-rich-text-html
        note: null
        options:
          customFormats:
            - title: Highlight
              inline: span
              classes: highlight
              styles:
                color: "#FDC33A"
          tinymceOverrides:
            forced_root_block: false
          toolbar:
            - bold
            - italic
        readonly: false
        required: false
        sort: 8
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: socials_title
        table: linotype_block__footers
        data_type: text
        default_value: null
        max_length: 65535
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__footers
      field: sort
      type: integer
      meta:
        collection: linotype_block__footers
        conditions: null
        display: null
        display_options: null
        field: sort
        group: null
        hidden: true
        interface: input
        note: null
        options: null
        readonly: false
        required: false
        sort: 2
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: sort
        table: linotype_block__footers
        data_type: int
        default_value: null
        max_length: null
        numeric_precision: 10
        numeric_scale: 0
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__footers
      field: status
      type: string
      meta:
        collection: linotype_block__footers
        conditions: null
        display: labels
        display_options:
          choices:
            - text: $t:published
              value: published
              background: var(--primary)
              foreground: "#FFFFFF"
            - text: $t:draft
              value: draft
              background: "#D3DAE4"
              foreground: "#18222F"
            - text: $t:archived
              value: archived
              background: var(--warning)
              foreground: "#FFFFFF"
          showAsDot: true
        field: status
        group: null
        hidden: false
        interface: select-dropdown
        note: null
        options:
          choices:
            - text: $t:published
              value: published
            - text: $t:draft
              value: draft
            - text: $t:archived
              value: archived
          icon: public
          placeholder: Select a block status
        readonly: false
        required: true
        sort: 4
        special: null
        translations: null
        validation: null
        validation_message: null
        width: half
      schema:
        name: status
        table: linotype_block__footers
        data_type: varchar
        default_value: published
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__footers
      field: sublinks
      type: json
      meta:
        collection: linotype_block__footers
        conditions: null
        display: formatted-json-value
        display_options:
          format: "{{title}}"
        field: sublinks
        group: null
        hidden: false
        interface: list
        note: null
        options:
          fields:
            - meta:
                type: string
                field: title
                required: true
                interface: input
              name: title
              type: string
              field: title
            - meta:
                type: string
                field: url
                required: true
                interface: input
              name: url
              type: string
              field: url
          template: "{{title}}"
        readonly: false
        required: false
        sort: 12
        special:
          - cast-json
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: sublinks
        table: linotype_block__footers
        data_type: longtext
        default_value: null
        max_length: 4294967295
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__footers
      field: subscription_form_url
      type: string
      meta:
        collection: linotype_block__footers
        conditions: null
        display: null
        display_options: null
        field: subscription_form_url
        group: null
        hidden: false
        interface: input
        note: The URL for submitting newsletter subscriptions.
        options:
          placeholder: https://
        readonly: false
        required: false
        sort: 10
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: subscription_form_url
        table: linotype_block__footers
        data_type: varchar
        default_value: null
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
  relations: []
