id: loop
version: 1
parent:
children:
  - loop_item
snapshot:
  collections:
    - collection: linotype_block__loop
      meta:
        accountability: all
        archive_app_filter: true
        archive_field: status
        archive_value: archived
        collapse: open
        collection: linotype_block__loop
        color: null
        display_template: "{{reference}}"
        group: linotype_blocks
        hidden: false
        icon: refresh
        item_duplication_fields: []
        note: ""
        singleton: false
        sort: 3
        sort_field: sort
        translations:
          - language: en-US
            translation: Loop
            plural: Loops
            singular: Loop
        unarchive_value: draft
      schema:
        name: linotype_block__loop
  fields:
    - collection: linotype_block__loop
      field: collection
      type: string
      meta:
        collection: linotype_block__loop
        conditions: null
        display: null
        display_options: null
        field: collection
        group: null
        hidden: false
        interface: input
        note: null
        options: null
        readonly: false
        required: false
        sort: null
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: collection
        table: linotype_block__loop
        data_type: varchar
        default_value: null
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__loop
      field: id
      type: integer
      meta:
        collection: linotype_block__loop
        conditions: null
        display: null
        display_options: null
        field: id
        group: null
        hidden: true
        interface: numeric
        note: null
        options: null
        readonly: true
        required: false
        sort: null
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: id
        table: linotype_block__loop
        data_type: integer
        default_value: null
        max_length: null
        numeric_precision: null
        numeric_scale: null
        is_nullable: false
        is_unique: false
        is_primary_key: true
        is_generated: false
        generation_expression: null
        has_auto_increment: true
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__loop
      field: reference
      type: string
      meta:
        collection: linotype_block__loop
        conditions: null
        display: raw
        display_options: null
        field: reference
        group: null
        hidden: false
        interface: input
        note: null
        options:
          iconLeft: flag
          placeholder: Define a unique reference for this block
          trim: true
        readonly: false
        required: true
        sort: 11
        special: null
        translations:
          - language: en-US
            translation: Reference
        validation: null
        validation_message: null
        width: half
      schema:
        name: reference
        table: linotype_block__loop
        data_type: varchar
        default_value: null
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__loop
      field: sort
      type: integer
      meta:
        collection: linotype_block__loop
        conditions: null
        display: null
        display_options: null
        field: sort
        group: null
        hidden: true
        interface: input
        note: null
        options: null
        readonly: false
        required: false
        sort: 11
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: sort
        table: linotype_block__loop
        data_type: integer
        default_value: null
        max_length: null
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__loop
      field: status
      type: string
      meta:
        collection: linotype_block__loop
        conditions: null
        display: labels
        display_options:
          choices:
            - text: $t:published
              value: published
              background: var(--primary)
              foreground: "#FFFFFF"
            - text: $t:draft
              value: draft
              background: "#D3DAE4"
              foreground: "#18222F"
            - text: $t:archived
              value: archived
              background: var(--warning)
              foreground: "#FFFFFF"
          showAsDot: true
        field: status
        group: null
        hidden: false
        interface: select-dropdown
        note: null
        options:
          choices:
            - text: $t:published
              value: published
            - text: $t:draft
              value: draft
            - text: $t:archived
              value: archived
          icon: public
          placeholder: Select a block status
        readonly: false
        required: true
        sort: 11
        special: null
        translations: null
        validation: null
        validation_message: null
        width: half
      schema:
        name: status
        table: linotype_block__loop
        data_type: varchar
        default_value: published
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__loop
      field: template
      type: text
      meta:
        collection: linotype_block__loop
        conditions: null
        display: null
        display_options: null
        field: template
        group: null
        hidden: false
        interface: textarea
        note: null
        options: null
        readonly: false
        required: false
        sort: null
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: template
        table: linotype_block__loop
        data_type: text
        default_value: null
        max_length: null
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
  relations: []
