version: 1

name: loop

meta:
  translations:
    - language: en-US
      translation: Loop
      plural: Loops
      singular: Loop
  icon: refresh
  color: null
  hidden: false
  note: ''
  sort: 1

fields:

  - name: collection
    type: string
    meta:
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
      validation: null
      validation_message: null

  - name: template
    type: text
    meta:
      special: null
      interface: textarea
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
      validation: null
      validation_message: null

  