version: 1
directus: 9.22.4

collections:

  - collection: linotype_content__articles
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: status
      archive_value: archived
      collapse: open
      collection: linotype_content__articles
      color: null
      display_template: '{{title}}'
      group: linotype_contents
      hidden: false
      icon: article
      item_duplication_fields:
        - content
        - title
      note: null
      singleton: false
      sort: 1
      sort_field: null
      translations:
        - plural: Articles
          language: en-US
          singular: Article
          translation: Articles
      unarchive_value: draft
    schema:
      collation: utf8mb4_unicode_ci
      comment: ''
      engine: InnoDB
      name: linotype_content__articles
      schema: superdock_db_1

fields:

  - collection: linotype_content__articles
    field: content
    meta:
      collection: linotype_content__articles
      conditions: null
      display: null
      display_options: null
      field: content
      group: null
      hidden: false
      interface: input-rich-text-html
      note: null
      options: null
      readonly: false
      required: false
      sort: 9
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: text
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 65535
      name: content
      numeric_precision: null
      numeric_scale: null
      table: linotype_content__articles
    type: text

  - collection: linotype_content__articles
    field: date_created
    meta:
      collection: linotype_content__articles
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 3
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: timestamp
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_created
      numeric_precision: null
      numeric_scale: null
      table: linotype_content__articles
    type: timestamp

  - collection: linotype_content__articles
    field: date_updated
    meta:
      collection: linotype_content__articles
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      sort: 4
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: timestamp
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: date_updated
      numeric_precision: null
      numeric_scale: null
      table: linotype_content__articles
    type: timestamp

  - collection: linotype_content__articles
    field: id
    meta:
      collection: linotype_content__articles
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: int unsigned
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: true
      is_generated: false
      is_nullable: false
      is_primary_key: true
      is_unique: false
      max_length: null
      name: id
      numeric_precision: 10
      numeric_scale: 0
      table: linotype_content__articles
    type: integer

  - collection: linotype_content__articles
    field: sort
    meta:
      collection: linotype_content__articles
      conditions: null
      display: null
      display_options: null
      field: sort
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      comment: ''
      data_type: int
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: null
      name: sort
      numeric_precision: 10
      numeric_scale: 0
      table: linotype_content__articles
    type: integer

  - collection: linotype_content__articles
    field: status
    meta:
      collection: linotype_content__articles
      conditions: null
      display: labels
      display_options:
        choices:
          - text: $t:published
            value: published
            background: var(--primary)
            foreground: '#FFFFFF'
          - text: $t:draft
            value: draft
            background: '#D3DAE4'
            foreground: '#18222F'
          - text: $t:archived
            value: archived
            background: var(--warning)
            foreground: '#FFFFFF'
        showAsDot: true
      field: status
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - text: $t:published
            value: published
          - text: $t:draft
            value: draft
          - text: $t:archived
            value: archived
      readonly: false
      required: false
      sort: 8
      special: null
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: varchar
      default_value: draft
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: false
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: status
      numeric_precision: null
      numeric_scale: null
      table: linotype_content__articles
    type: string

  - collection: linotype_content__articles
    field: title
    meta:
      collection: linotype_content__articles
      conditions: null
      display: null
      display_options: null
      field: title
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      sort: 7
      special: null
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: null
      foreign_key_table: null
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 255
      name: title
      numeric_precision: null
      numeric_scale: null
      table: linotype_content__articles
    type: string

  - collection: linotype_content__articles
    field: user_created
    meta:
      collection: linotype_content__articles
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 5
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: id
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: user_created
      numeric_precision: null
      numeric_scale: null
      table: linotype_content__articles
    type: string

  - collection: linotype_content__articles
    field: user_updated
    meta:
      collection: linotype_content__articles
      conditions: null
      display: user
      display_options: null
      field: user_updated
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      sort: 6
      special:
        - user-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      comment: ''
      data_type: varchar
      default_value: null
      foreign_key_column: id
      foreign_key_table: directus_users
      generation_expression: null
      has_auto_increment: false
      is_generated: false
      is_nullable: true
      is_primary_key: false
      is_unique: false
      max_length: 36
      name: user_updated
      numeric_precision: null
      numeric_scale: null
      table: linotype_content__articles
    type: string


relations:

  - collection: linotype_content__articles
    field: user_created
    meta:
      junction_field: null
      many_collection: linotype_content__articles
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_created
      constraint_name: linotype_content__articles_user_created_foreign
      foreign_key_column: id
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: linotype_content__articles
  - collection: linotype_content__articles
    field: user_updated
    meta:
      junction_field: null
      many_collection: linotype_content__articles
      many_field: user_updated
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    related_collection: directus_users
    schema:
      column: user_updated
      constraint_name: linotype_content__articles_user_updated_foreign
      foreign_key_column: id
      foreign_key_table: directus_users
      on_delete: NO ACTION
      on_update: NO ACTION
      table: linotype_content__articles
