id: forms
version: 1
snapshot:
  collections:
    - collection: linotype_block__forms
      meta:
        accountability: all
        archive_app_filter: true
        archive_field: status
        archive_value: archived
        collapse: open
        collection: linotype_block__forms
        color: null
        display_template: "{{reference}}"
        group: linotype_blocks
        hidden: false
        icon: edit_attributes
        item_duplication_fields: []
        note: ""
        preview_url: null
        singleton: false
        sort: 10
        sort_field: sort
        translations:
          - plural: Forms
            language: en-US
            singular: Form
            translation: Forms
        unarchive_value: draft
        versioning: false
      schema:
        name: linotype_block__forms
  fields:
    - collection: linotype_block__forms
      field: address
      type: text
      meta:
        collection: linotype_block__forms
        conditions: null
        display: null
        display_options: null
        field: address
        group: null
        hidden: false
        interface: input-multiline
        note: null
        options:
          toolbar:
            - blockquote
            - bold
            - bullist
            - code
            - customImage
            - customLink
            - customMedia
            - fullscreen
            - h1
            - h2
            - h3
            - hr
            - numlist
            - removeformat
        readonly: false
        required: false
        sort: 7
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: address
        table: linotype_block__forms
        data_type: text
        default_value: null
        max_length: 65535
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__forms
      field: description
      type: text
      meta:
        collection: linotype_block__forms
        conditions: null
        display: null
        display_options: null
        field: description
        group: null
        hidden: false
        interface: input-rich-text-html
        note: null
        options:
          toolbar:
            - bold
            - customLink
            - italic
            - strikethrough
            - subscript
            - superscript
            - underline
        readonly: false
        required: false
        sort: 6
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: description
        table: linotype_block__forms
        data_type: text
        default_value: null
        max_length: 65535
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__forms
      field: email_from
      type: string
      meta:
        collection: linotype_block__forms
        conditions: null
        display: null
        display_options: null
        field: email_from
        group: null
        hidden: false
        interface: input
        note: null
        options:
          iconLeft: alternate_email
          templateType: email
          transform: lower
        readonly: false
        required: true
        sort: 9
        special: null
        translations: null
        validation:
          _and:
            - email_from:
                _contains: "@"
        validation_message: null
        width: half
      schema:
        name: email_from
        table: linotype_block__forms
        data_type: varchar
        default_value: null
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__forms
      field: email_to
      type: string
      meta:
        collection: linotype_block__forms
        conditions: null
        display: null
        display_options: null
        field: email_to
        group: null
        hidden: false
        interface: input
        note: null
        options:
          iconLeft: alternate_email
          templateType: email
          transform: lower
        readonly: false
        required: true
        sort: 10
        special: null
        translations: null
        validation:
          _and:
            - email_to:
                _contains: "@"
        validation_message: null
        width: half
      schema:
        name: email_to
        table: linotype_block__forms
        data_type: varchar
        default_value: null
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__forms
      field: id
      type: integer
      meta:
        collection: linotype_block__forms
        conditions: null
        display: null
        display_options: null
        field: id
        group: null
        hidden: true
        interface: numeric
        note: null
        options: null
        readonly: true
        required: false
        sort: 1
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: id
        table: linotype_block__forms
        data_type: int unsigned
        default_value: null
        max_length: null
        numeric_precision: 10
        numeric_scale: 0
        is_nullable: false
        is_unique: false
        is_primary_key: true
        is_generated: false
        generation_expression: null
        has_auto_increment: true
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__forms
      field: phone
      type: string
      meta:
        collection: linotype_block__forms
        conditions: null
        display: null
        display_options: null
        field: phone
        group: null
        hidden: false
        interface: input
        note: null
        options:
          iconLeft: phone_enabled
        readonly: false
        required: false
        sort: 8
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: phone
        table: linotype_block__forms
        data_type: varchar
        default_value: null
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__forms
      field: reference
      type: string
      meta:
        collection: linotype_block__forms
        conditions: null
        display: raw
        display_options: null
        field: reference
        group: null
        hidden: false
        interface: input
        note: null
        options:
          iconLeft: flag
          placeholder: Define a unique reference for this block
          trim: true
        readonly: false
        required: true
        sort: 3
        special: null
        translations:
          - language: en-US
            translation: Reference
        validation: null
        validation_message: null
        width: half
      schema:
        name: reference
        table: linotype_block__forms
        data_type: varchar
        default_value: null
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__forms
      field: sort
      type: integer
      meta:
        collection: linotype_block__forms
        conditions: null
        display: null
        display_options: null
        field: sort
        group: null
        hidden: true
        interface: input
        note: null
        options: null
        readonly: false
        required: false
        sort: 2
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: sort
        table: linotype_block__forms
        data_type: int
        default_value: null
        max_length: null
        numeric_precision: 10
        numeric_scale: 0
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__forms
      field: status
      type: string
      meta:
        collection: linotype_block__forms
        conditions: null
        display: labels
        display_options:
          choices:
            - text: $t:published
              value: published
              background: var(--primary)
              foreground: "#FFFFFF"
            - text: $t:draft
              value: draft
              background: "#D3DAE4"
              foreground: "#18222F"
            - text: $t:archived
              value: archived
              background: var(--warning)
              foreground: "#FFFFFF"
          showAsDot: true
        field: status
        group: null
        hidden: false
        interface: select-dropdown
        note: null
        options:
          choices:
            - text: $t:published
              value: published
            - text: $t:draft
              value: draft
            - text: $t:archived
              value: archived
          icon: public
          placeholder: Select a block status
        readonly: false
        required: true
        sort: 4
        special: null
        translations: null
        validation: null
        validation_message: null
        width: half
      schema:
        name: status
        table: linotype_block__forms
        data_type: varchar
        default_value: published
        max_length: 255
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__forms
      field: template
      type: text
      meta:
        collection: linotype_block__forms
        conditions: null
        display: null
        display_options: null
        field: template
        group: null
        hidden: false
        interface: input-rich-text-html
        note: null
        options:
          toolbar:
            - bold
            - bullist
            - code
            - customLink
            - fullscreen
            - italic
            - numlist
            - underline
        readonly: false
        required: false
        sort: 12
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: template
        table: linotype_block__forms
        data_type: text
        default_value: null
        max_length: 65535
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
    - collection: linotype_block__forms
      field: title
      type: text
      meta:
        collection: linotype_block__forms
        conditions: null
        display: null
        display_options: null
        field: title
        group: null
        hidden: false
        interface: input
        note: null
        options: null
        readonly: false
        required: false
        sort: 5
        special: null
        translations: null
        validation: null
        validation_message: null
        width: full
      schema:
        name: title
        table: linotype_block__forms
        data_type: text
        default_value: null
        max_length: 65535
        numeric_precision: null
        numeric_scale: null
        is_nullable: true
        is_unique: false
        is_primary_key: false
        is_generated: false
        generation_expression: null
        has_auto_increment: false
        foreign_key_table: null
        foreign_key_column: null
  relations: []
