version: 1

name: comments

meta:
  translations:
    - language: en-US
      translation: Comment
      plural: Comments
      singular: Comment
  icon: chat
  color: null
  hidden: false
  note: ''
  sort: 1

fields:

  - name: collection
    type: string
    meta:
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
      validation: null
      validation_message: null

collections:

  - name: collection
    type: string
    meta:
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
      validation: null
      validation_message: null


  