version: 1

name: nav

meta:
  translations:
    - language: en-US
      translation: Navigation
      plural: Navigations
      singular: Navigation
  icon: menu
  color: null
  hidden: false
  note: ''
  sort: 1

fields:

  - name: title
    type: string
    meta:
      interface: input